version: '3.8'
services:
  config-service:
    build:
      context: ./backend/config-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  gateway-service:
    build:
      context: ./backend/gateway-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka

  auth-service:
    build:
      context: ./backend/auth-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka

  market-data-service:
    build:
      context: ./backend/market-data-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka

  predictions-service:
    build:
      context: ./backend/predictions-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka

  eureka-service:
    build:
      context: ./backend/eureka-service
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
